version: 1.0
os: linux 
files:
  - source: *  
  destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/reload_server
      timeout: 300
      runas: root
